# Nome da Aplicação
spring.application.name=LumeEstoque

# Configuração de Conexão com PostgreSQL / Supabase via Spring JDBC (Sem JPA / Hibernate)
# Conexão Direta PostgreSQL (Porta 5432): jdbc:postgresql://db.pssrggtqmphcpqbdhjex.supabase.co:5432/postgres?sslmode=require (usuário: postgres)
# Conexão Pooler Supabase (Porta 6543 - Compatível IPv4/IPv6): jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require (usuário: postgres.pssrggtqmphcpqbdhjex)
spring.datasource.url=${SUPABASE_DB_URL:jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require}
spring.datasource.username=${SUPABASE_DB_USERNAME:postgres.pssrggtqmphcpqbdhjex}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
