spring.application.name=projeto-joias

# ==========================================
# CONEXÃO COM O POSTGRESQL DO SUPABASE
# ==========================================

spring.datasource.url=${DB_URL:jdbc:postgresql://db.tbrjmxpxfkfdrbmiamtm.supabase.co:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres.tbrjmxpxfkfdrbmiamtm}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# Supabase API / Rest Key
supabase.url=${SUPABASE_URL:https://tbrjmxpxfkfdrbmiamtm.supabase.co}
supabase.key=${SUPABASE_KEY:https://tbrjmxpxfkfdrbmiamtm.supabase.co/rest/v1/}
supabase.rest.url=${SUPABASE_REST_URL:https://tbrjmxpxfkfdrbmiamtm.supabase.co/rest/v1/}


# ==========================================
# JPA / HIBERNATE
# ==========================================

# Cria/atualiza as tabelas de acordo com as entidades
spring.jpa.hibernate.ddl-auto=update

# Dialeto PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mostra os comandos SQL no console
spring.jpa.show-sql=true

# Formata os comandos SQL no console
spring.jpa.properties.hibernate.format_sql=true

# Evita problemas de sessão aberta durante a resposta
spring.jpa.open-in-view=false
