spring.application.name=projeto-joias

# ==========================================
# SUPABASE CONFIGURATION
# ==========================================

supabase.url=${SUPABASE_URL:https://pssrggtqmphcpqbdhjex.supabase.co}
supabase.rest.url=${SUPABASE_REST_URL:https://pssrggtqmphcpqbdhjex.supabase.co/rest/v1/}
supabase.jwks.url=${SUPABASE_JWKS_URL:https://pssrggtqmphcpqbdhjex.supabase.co/auth/v1/.well-known/jwks.json}
supabase.project.ref=${SUPABASE_PROJECT_REF:pssrggtqmphcpqbdhjex}
supabase.secret.key=${SUPABASE_SECRET_KEY:}

# ==========================================
# CONEXÃO COM O POSTGRESQL DO SUPABASE (DATASOURCE)
# ==========================================

spring.datasource.url=${DB_URL:${SUPABASE_DB_URL:jdbc:postgresql://db.pssrggtqmphcpqbdhjex.supabase.co:5432/postgres}}
spring.datasource.username=${DB_USERNAME:${SUPABASE_DB_USER:postgres}}
spring.datasource.password=${DB_PASSWORD:${SUPABASE_DB_PASSWORD:}}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}

# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
